//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.03 at 05:20:58 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://github.com/snowtoslow/SOAP", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package https.github_com.snowtoslow.soap;
